// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Finite$LambdaStreams = require("lambda-streams/lambda_streams/src/Finite.bs.js");

Finite$LambdaStreams.Sync.pipe(Curry._1(Finite$LambdaStreams.Sync.make_output, (function (prim) {
            console.log(prim);
            
          })), Finite$LambdaStreams.Sync.map((function (param) {
            return (param << 1);
          }), Finite$LambdaStreams.Sync.from_list({
              hd: 1,
              tl: {
                hd: 1,
                tl: {
                  hd: 2,
                  tl: {
                    hd: 3,
                    tl: {
                      hd: 5,
                      tl: {
                        hd: 8,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }
            })));

/*  Not a pure module */
